version: '3.9'

services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    # In production you typically avoid exposing DB port publicly
    # ports:
    #   - "5432:5432"

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: skeleton-backend-nestjs:prod
    environment:
      NODE_ENV: production
      PORT: 3000
      APP_NAME: SkeletonBackend
      CORE_DATABASE_TYPE: postgres
      CORE_DATABASE_HOST: db
      CORE_DATABASE_PORT: '5432'
      CORE_DATABASE_USERNAME: postgres
      CORE_DATABASE_PASSWORD: postgres
      CORE_DATABASE_NAME: postgres
      CORE_DATABASE_SYNCHRONIZE: 'false'
      CORE_DATABASE_LOGGING: 'false'
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  pgdata:
